### ISSUE TITLE
Problem step 3 Node.js

### ISSUE THREAD

**Issue by RicardoMan** [ryanjgill/mkr1000#4]
Thank you very much for your contribution, I have the following questions.

ricardomanriquez@MacBook-Pro-de-Ricardo mkr1000-PlantMS % npm node-sass -v
6.4.1
ricardomanriquez@MacBook-Pro-de-Ricardo ~ % node -v
v8.16.0
ricardomanriquez@MacBook-Pro-de-Ricardo ~ % npm -v
6.4.1

npm dependencies are installed before in our folder or after npm run build: css?

likewise when I run npm install in my directory, I have the following error:

`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: serialport@3.1.2 (node_modules/johnny-five/node_modules/firmata/node_modules/serialport):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: serialport@3.1.2 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: serialport@4.0.7 (node_modules/johnny-five/node_modules/serialport):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: serialport@4.0.7 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@2.1.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@2.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ricardomanriquez/.npm/_logs/2020-07-27T14_54_10_091Z-debug.log
ricardomanriquez@MacBook-Pro-de-Ricardo mkr1000-PlantMS % npm install -g node-sass
`
when i run npm run build: css

`Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/Users/ricardomanriquez/Downloads/mkr1000-PlantMS/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/ricardomanriquez/Downloads/mkr1000-PlantMS/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ricardomanriquez/Downloads/mkr1000-PlantMS/node_modules/node-sass/bin/node-sass:11:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mkr1000@0.0.0 build:css: `node-sass public/stylesheets/*.scss --output public/stylesheets`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mkr1000@0.0.0 build:css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ricardomanriquez/.npm/_logs/2020-07-27T15_06_50_944Z-debug.log
`

Thanks!!

**Comment by ryanjgill** [comment]
I was thinking rolling back the node version would help but it looks like all the dependencies are having issues when I change the node versions. It fixes 1 but causes issues with another.

I'm gonna take a look later tonight when I get off work and see if there is anything I can do to get this project back up and running.

**Comment by RicardoMan** [comment]
thank you! I will be attentive

**Comment by ryanjgill** [comment]
@RicardoMan I've made some changes to the master branch. I was able to get it all working again with the latest updated dependencies. I did end up changing the static ip address since I've updated routers.

I'm using `Node v8.16.0`.

**Comment by RicardoMan** [comment]
thanks for the answer, now I improve everything, the only thing that when I generate the 'npm start' tells me the following:

`Unable to connect!
Please make sure you have the latest StandardFirmataWifi sketch loaded on the MKR1000`

Is there something new that I need to change in the firmdata?

Thanks !!!

**Comment by ryanjgill** [comment]
That means the app is not finding the mkr1000 on the local network. To make sure you can connect to your network, you can uncomment the line in standardFirmataWifi sketch that will enable the serial console. In the StandardFirmataWifi sketch in the Arduino IDE you would uncomment this line:

```
/*
 * Uncomment the #define SERIAL_DEBUG line below to receive serial output messages relating to your
 * connection that may help in the event of connection issues. If defined, some boards may not begin
 * executing this sketch until the Serial console is opened.
 */
#define SERIAL_DEBUG
```

uncommenting that line allows you to view the console output in the Arduino IDE. I would uncomment that line and leave the static IP address setting in wifiConf.h commented out so it connects to your network and gets an IP address that is free. Then you can use that address as your static ip address and you would have to update the `app.js` to match your static ip.

You must comment out `//#define SERIAL_DEBUG` and re-upload the sketch for the app to work.

**Comment by RicardoMan** [comment]
apparently it is connected

StandardFirmataWiFi will attempt a WiFi connection using the WiFi 101 library.
Using static IP: 192.168.100.XX
Attempting to connect to WPA SSID: Rye
WiFi setup done
SSID: Rye
IP Address: 192.168.100.XX
signal strength (RSSI): -47 dBm

**Comment by ryanjgill** [comment]
perfect, now you can use that as the static ip and make sure to recomment out the serial debug line. You should only need to update it on the line here in `app.js` to match that ip:

```
// set options to match Firmata config for wifi
// using MKR1000 with WiFi101
const options = {
  host: '192.168.100.XX',
  port: 3030
}
```

**Comment by RicardoMan** [comment]
yes, modify the app.js with the static ip, 

// set options to match Firmata config for wifi
// using MKR1000 with WiFi101
const options = {
  host: '192.168.100.XX',
  port: 3030
}

but it still says

`Unable to connect! Please make sure you have the latest StandardFirmataWifi sketch loaded on the MKR1000`

I will try to update my libraries

**Comment by RicardoMan** [comment]
What version of the firmata do you have on your arduino?

**Comment by ryanjgill** [comment]
its just the standardFirmataWifi sketch from the examples. it has this date in the comments at the top:

```
Last updated August 17th, 2017
```

**Comment by ryanjgill** [comment]
Did you make sure to re comment out line `#define SERIAL_DEBUG` in the standardFirmataWifi sketch and reupload to the mkr1000?

it should be `//#define SERIAL_DEBUG`.

**Comment by RicardoMan** [comment]
yes, it is working with the //

**Comment by RicardoMan** [comment]
Well, I could not successfully achieve my goal, I tried many times everything mentioned and I could not connect to the server.

re install the matrix folder again and again, re install node, reset the arduino, update libraries, etc.

anyway I appreciate your support. Thank you.

**Comment by ryanjgill** [comment]
Sorry @RicardoMan. I feel like you are really close to getting it going. If you can see that the Arduino is connecting to your network, we just need to get the connection between the node app and the MKR1000 working. You should only need to match that ip for the connection to work. 

Some of the problems I've ran across are networks not allowing peer to peer. Some universities and other public routers don't allow you to do peer to peer. If you are at home this probably isn't the problem.

Another problem could be that the Arduino is connecting to a different network than the computer running the Node app?

**Comment by RicardoMan** [comment]
if I use a different port? maybe port 3030 has it busy with another virtual machine

**Comment by ryanjgill** [comment]
Thats worth a shot, just make sure they match in the `wifiConfig.h` and the `app.js`.

**Comment by RicardoMan** [comment]
Hey Men , I Did!

update the firmware and also had to configure the file mkr1000wifi.js (maybe that was the problem)

https://www.arduino.cc/en/Tutorial/FirmwareUpdater

I will continue in the project, thanks buddy

**Comment by RicardoMan** [comment]
I want to thank you because it works perfect! the only thing I can mention is that the squematic is wrong with the light sensor with the soil moisture sensor.

My last question, if I wanted the temperature in Celsius, what file should I focus on?

The temperature sensor varies greatly in temperature, should I calibrate it?

Thanks again

**Comment by ryanjgill** [comment]
Awesome. Glad you stuck with it and got it going.

For the temperature change you would need to update the following function in `app.js`:

```
// get temperature measurement
function getTemp(tempSensor) {
  return Math.round(tempSensor.fahrenheit - 25)
}
```

to 

```
// get temperature measurement
function getTemp(tempSensor) {
  return Math.round(tempSensor.celsius)
}
```

You can then replace all the spots where `°F` occurs with `°C`.

Its in a few spots in these javascript files:  `chart.js`, `tempDetailChart.js`
and in a few pug templates: `index.pug` and `temperature.pug`. 


As far as the temperature sensor calibration, mine was off by a large amount so I adjusted the value by subtracting 25 to get it closer to the actual temp.
